export const RestaurentData = [
	 
	{	id: "28768",
		name: "Domino's Pizza",
		ImageId: "https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=600",
		locality: "Kachiguda Main Road",
		areaName: "Hyderabad",
		costForTwo: "₹G00 for two",
		cuisines: [
			"Pizzas",
			"Italian",
			"Pastas",
			"Desserts" ],
        AvgRating : ".5"      } ,
        //hotel 2 
        {	id: "28768",
        name: "Rajesh FOod Zone",
        ImageId: "https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=600",
        locality: "Kachiguda Main Road",
        areaName: "Kachiguda",
        costForTwo: "₹400 for two",
        cuisines: [
            
           
            "Grill",
            "Hyderabadi",
            "Indian" ,
            "Punjabi",
             ],
          AvgRating : ".5"   } ,
          //hotel 3 
          {	id: "28768",
          name: "Good NIght Tiffins",
          ImageId: "https://images.pexels.com/photos/4559174/pexels-photo-4559174.jpeg?auto=compress&cs=tinysrgb&w=600",
          locality: "Kachiguda Main Road",
          areaName: "Kachiguda",
          costForTwo: "₹400 for two",
          cuisines: [
             "Pizzas",
             "Italian",
             "Pastas",
             "Desserts" ],
            AvgRating : ".5"      } ,
            //hotel 4
            {	id: "28768",
            name: "Healthy Foods",
            ImageId: "https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&cs=tinysrgb&w=600",
            locality: "Kachiguda Main Road",
            areaName: "Kachiguda",
            costForTwo: "₹400 for two",
            cuisines: [
               "Ragi Malt" ,
               "Ragi Sangati" ,
               "Natu Kodi"

                ],
              AvgRating : "4.5"      } ,
              //hotel 5
              {	id: "28768",
              name: "Tea Point",
              ImageId: "https://images.pexels.com/photos/12823962/pexels-photo-12823962.jpeg?auto=compress&cs=tinysrgb&w=600",
              locality: "Kachiguda Main Road",
              areaName: "Kkd",
              costForTwo: "₹100 for two",
              cuisines: [
                 "Tea" ,
               "coffee" ,
                 "Boost",
               "Horlicks" , ],
                AvgRating : "4.5"  } 
              ,
              {	id: "28768",
              name: "Carnival Food",
              ImageId:  "https://i.pinimg.com/564x/9d/24/15/9d2415e2b19e040868960666aa1f3738.jpg",
              locality: "Kachiguda Main Road",
              areaName: "Kkd",
              costForTwo: "₹100 for two",
              cuisines: [
                "Continental",
                "North Indian",
                "Desserts",
                "American", ],
                AvgRating : "3.5"  } ,

                {	id: "28768",
                name: "Michel Foods ",
                ImageId:  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vkrgirkk7hdyl4cfqi85",
                locality: "Kachiguda Main Road",
                areaName: "Kkd",
                costForTwo: "₹100 for two",
                cuisines: [
                  "Continental",
                  "North Indian",
                  "Desserts",
                  "American", ],
                  AvgRating : "4.5"  } ,

                  {	id: "28768",
                  name: "4 A.M Food HOUSE",
                  ImageId:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIHAVhAp1FmTWsSzwCt2IkZur7AtGm1Qq0gw&usqp=CAU",
                  locality: "Kachiguda Main Road",
                  areaName: "Kkd",
                  costForTwo: "₹100 for two",
                  cuisines: [
                    "Beverages",
                    "Biryani",
                    "Chinese",
                       ],
                    AvgRating : "4.5"  } ,
                    {	id: "28768",
                    name: " 99 Rupee Food Zone ",
                    ImageId:  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/zwrzytw9sr3ovoc9yott",
                    locality: "Kachiguda Main Road",
                    areaName: "Kkd",
                    costForTwo: "₹100 for two",
                    cuisines: [ "Mediterranean",
                    "Mexican",
                    "Mughlai",
                        
                       ],
                      AvgRating : "4.5"  } ,
                      {	id: "28768",
                      name: "24/7 Tiffins",
                      ImageId:  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ebg0qtutkmzzbsxkd19z",
                      locality: "Kachiguda Main Road",
                      areaName: "Kkd",
                      costForTwo: "₹100 for two",
                      cuisines: [ "Idli" ,
                      "Dosa",
                      "Vada" ,
                      "Puri" ,
                      "Chapathi" ,
                      "Upma"
                     
                         ],
                        AvgRating : "4.5"  } ,   
                        
                        {	id: "28768",
                      name: "Dosa Hub",
                      ImageId:  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/v1674029850/PC_Creative%20refresh/3D_bau/banners_new/Dosa.png",
                      locality: "Kachiguda Main Road",
                      areaName: "Kkd",
                      costForTwo: "₹100 for two",
                      cuisines: [ "Plain Dosa" ,
                                 "Masala Dosa" , "EggDosa" , "Chicken Dosa"
                         ],
                        AvgRating : "4.5"} ,

                        {	id: "28768",
                        name: " Himalayas ",
                        ImageId:  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/zwrzytw9sr3ovoc9yott",
                        locality: "Kachiguda Main Road",
                        areaName: "Kkd",
                        costForTwo: "₹100 for two",
                        cuisines: [ "Butter Stotch"  ,
                        "PineApple" , "StrawBerry" ,"Vanilla"
                          ],
                           AvgRating : "3.5"   } ] 